### ISSUE TITLE
game versions in correct in toc files

### ISSUE THREAD

**Issue by MyTechnoHunter** [acharnoz/DBM-VoicePack-FrenchFemale#1]
the game version in the toc files for vanilla and wrath have been switched.. the game version for wrath is in the vanilla file and the game version for vanilla is in the wrath file.
![image](https://github.com/acharnoz/DBM-VoicePack-FrenchFemale/assets/55214545/14b0c70e-7039-4d51-8aaf-73d9e7f078ca)

**Comment by acharnoz** [comment]
Thanks for the feedback, it is corrected now normally.

**Comment by acharnoz** [comment]
the new version has been pushed
