### ISSUE TITLE
Warning message on login

### ISSUE THREAD

**Issue by Adal4** [acharnoz/DBM-VoicePack-FrenchFemale#4]
Warning message on login:

> <DBM> Il semble que votre paquet de voix DBM manque de sons supportés sur cette version de DBM. Certains sons d'alertes spéciales ne seront pas joués s'ils utilisent des voix non supportées par votre version. Téléchargez une nouvelle version du paquet de voix ou contactez l'auteur pour une mise à jour qui l'inclut.

WoW version: 4.4.1 (Cataclysm Classic), French client.
DBM: DBM Core 11.0.39, DBM Raids Cata r250, DBM Dungeons r178.

**Comment by acharnoz** [comment]
Thank you Adal4 for the report !
I converted the new audio file and i change the dbm version for audio files in my addon.
I just push the new versions of my packs, normally all will be ok soon.
Thanks !

**Comment by acharnoz** [comment]
addons are available on curse normally
